#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Detailed cropland extent--crop sown area diagnostic analysis.

This script is intentionally self-contained and verbose because it is the core
revision step used to separate two quantities that are frequently conflated in
large-scale agricultural land-use studies:

    C_it : physical cropland extent derived from CACD or another annual LULC map
    S_it : official statistical crop sown area, i.e. annual planting activity
    R_it : S_it / C_it, an agricultural-use intensity proxy

The script performs five tasks.

1. Read and harmonize province-by-year tables for cropland extent and crop sown
   area. The expected format is:

       FID | Province | 2000 | 2001 | ... | 2023

   The FID column is optional. Province names are standardized and tables are
   aligned before calculations.

2. Compute relative changes between a base year and an end year:

       gC_i = 100 * (C_i,end - C_i,base) / C_i,base
       gS_i = 100 * (S_i,end - S_i,base) / S_i,base
       DI_i = gS_i - gC_i

   Provinces with |relative change| <= stable threshold are treated as stable.
   The default threshold is ±5%, because stability should not be defined as
   exactly zero change in long-term national datasets.

3. Classify province-level coupling pathways between physical cropland extent
   and annual planting activity:

       C↑–S↑ : joint cropland gain and sown-area increase
       C≈–S↑ : intensified planting under stable cropland extent
       C↓–S↑ : intensified planting under land constraint
       ...

4. Decompose changes in crop sown area using the identity S = C × R:

       ΔS = R0 × ΔC + C0 × ΔR + ΔC × ΔR

   The terms are interpreted as:
       - cropland-extent effect
       - use-intensity effect
       - interaction effect

   This decomposition is exact for each province between base and end year, and
   can also be calculated annually at the national scale.

5. Export transparent tables and publication-ready diagnostic figures. The
   default figures include:
       - coupling typology scatter plot
       - national phase-space trajectory
       - cumulative decomposition of national sown-area change
       - robust temporal envelope for relative changes and use intensity

The script avoids causal language. It identifies diagnostic relationships and
pathways rather than claiming that cropland extent changes cause crop sown-area
changes.
"""

from __future__ import annotations

import argparse
import logging
import math
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable, Sequence

import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt
from matplotlib.lines import Line2D
from matplotlib.patches import Patch

# -----------------------------------------------------------------------------
# Publication-style constants
# -----------------------------------------------------------------------------

NAVY = "#173A5E"
BLUE = "#244C74"
TEAL = "#2A9D8F"
SAND = "#D9A441"
TERRACOTTA = "#A63A2B"
PLUM = "#6B4C88"
MOSS = "#5C7A66"
BROWN = "#8C6D31"
CHARCOAL = "#222222"
DARK_GRAY = "#555555"
MID_GRAY = "#C8C8C8"
LIGHT_GRAY = "#E9E9E9"
PALE_GRAY = "#F7F7F7"

COUPLING_ORDER = [
    "C↑–S↑",
    "C≈–S↑",
    "C↓–S↑",
    "C↑–S≈",
    "C≈–S≈",
    "C↓–S≈",
    "C↑–S↓",
    "C≈–S↓",
    "C↓–S↓",
]

COUPLING_NAMES = {
    "C↑–S↑": "Joint cropland gain and sown-area increase",
    "C≈–S↑": "Sown-area increase under stable cropland extent",
    "C↓–S↑": "Sown-area increase under declining cropland extent",
    "C↑–S≈": "Cropland gain with stable sown area",
    "C≈–S≈": "Stable utilization",
    "C↓–S≈": "Cropland loss with stable sown area",
    "C↑–S↓": "Cropland gain with sown-area decline",
    "C≈–S↓": "Sown-area decline under stable cropland extent",
    "C↓–S↓": "Dual decline",
}

COUPLING_COLORS = {
    "C↑–S↑": "#2A9D8F",
    "C≈–S↑": "#5C7A66",
    "C↓–S↑": "#173A5E",
    "C↑–S≈": "#7FB8A7",
    "C≈–S≈": "#D9A441",
    "C↓–S≈": "#B88A3B",
    "C↑–S↓": "#8E6FAE",
    "C≈–S↓": "#C76D3A",
    "C↓–S↓": "#A63A2B",
}

EFFECT_COLORS = {
    "Cropland-extent effect": NAVY,
    "Use-intensity effect": TEAL,
    "Interaction effect": SAND,
}


@dataclass
class DiagnosticOutputs:
    """Container with key dataframes generated by the workflow."""

    province_summary: pd.DataFrame
    national_timeseries: pd.DataFrame
    national_annual_decomposition: pd.DataFrame
    national_cumulative_decomposition: pd.DataFrame
    coupling_counts: pd.DataFrame
    temporal_diagnostics: pd.DataFrame


# -----------------------------------------------------------------------------
# Logging, style and I/O helpers
# -----------------------------------------------------------------------------


def configure_logging(verbose: bool = True) -> None:
    level = logging.INFO if verbose else logging.WARNING
    logging.basicConfig(
        level=level,
        format="%(asctime)s | %(levelname)s | %(message)s",
        datefmt="%H:%M:%S",
    )


def set_publication_style(dpi: int = 300) -> None:
    """Set conservative journal-friendly matplotlib defaults."""
    mpl.rcParams.update(
        {
            "font.family": "serif",
            "font.serif": ["Times New Roman", "Times", "DejaVu Serif"],
            "mathtext.fontset": "stix",
            "figure.dpi": dpi,
            "savefig.dpi": dpi,
            "figure.facecolor": "white",
            "axes.facecolor": "white",
            "axes.edgecolor": CHARCOAL,
            "axes.linewidth": 1.0,
            "axes.titlesize": 14,
            "axes.titleweight": "bold",
            "axes.labelsize": 12,
            "xtick.labelsize": 10,
            "ytick.labelsize": 10,
            "legend.fontsize": 9,
            "lines.linewidth": 2.2,
            "xtick.direction": "out",
            "ytick.direction": "out",
            "pdf.fonttype": 42,
            "ps.fonttype": 42,
            "axes.unicode_minus": False,
        }
    )


def despine(ax: mpl.axes.Axes) -> None:
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)


def panel_label(ax: mpl.axes.Axes, label: str, x: float = -0.10, y: float = 1.05) -> None:
    ax.text(
        x,
        y,
        label,
        transform=ax.transAxes,
        fontsize=14,
        fontweight="bold",
        ha="left",
        va="top",
        color="#111111",
    )


def save_figure(fig: mpl.figure.Figure, output_base: Path, formats: Sequence[str] = ("png", "pdf")) -> None:
    output_base.parent.mkdir(parents=True, exist_ok=True)
    for ext in formats:
        path = output_base.with_suffix(f".{ext}")
        fig.savefig(path, bbox_inches="tight", facecolor="white", edgecolor="none")
        logging.info("Saved figure: %s", path)
    plt.close(fig)


def detect_year_columns(df: pd.DataFrame, start_year: int, end_year: int) -> list[str]:
    expected = {str(y) for y in range(start_year, end_year + 1)}
    year_cols = [c for c in df.columns if str(c).strip() in expected]
    missing = sorted(expected - {str(c).strip() for c in year_cols})
    if missing:
        raise ValueError(f"Missing year columns: {missing[:10]}{'...' if len(missing) > 10 else ''}")
    return [str(y) for y in range(start_year, end_year + 1)]


def normalize_province_name(value: object) -> str:
    text = str(value).strip()
    text = re.sub(r"\s+", " ", text)
    text = text.replace("Province", "").replace("Autonomous Region", "")
    text = text.replace("Municipality", "").strip()
    return text


def read_year_table(
    path: str | Path,
    sheet_name: str | int | None,
    start_year: int,
    end_year: int,
    scale_to_kha: float = 1.0,
    province_column: str = "Province",
) -> pd.DataFrame:
    """Read a province-by-year table and return numeric values in kha."""
    path = Path(path)
    logging.info("Reading year table: %s", path)
    if path.suffix.lower() in {".xlsx", ".xls"}:
        df = pd.read_excel(path, sheet_name=sheet_name)
    else:
        df = pd.read_csv(path)

    if province_column not in df.columns:
        candidates = [c for c in df.columns if str(c).lower() in {"province", "name", "region"}]
        if candidates:
            province_column = candidates[0]
        else:
            raise ValueError(f"Province column {province_column!r} not found in {path}")

    df = df.copy()
    df["Province"] = df[province_column].map(normalize_province_name)
    year_cols = detect_year_columns(df, start_year, end_year)

    out = df[["Province"] + year_cols].copy()
    for col in year_cols:
        out[col] = pd.to_numeric(out[col], errors="coerce") * scale_to_kha
    if out[year_cols].isna().any().any():
        n_missing = int(out[year_cols].isna().sum().sum())
        raise ValueError(f"Table {path} contains {n_missing} missing/non-numeric year values.")
    if out["Province"].duplicated().any():
        duplicates = out.loc[out["Province"].duplicated(), "Province"].tolist()
        raise ValueError(f"Duplicated province names in {path}: {duplicates}")
    return out.sort_values("Province").reset_index(drop=True)


def write_table(df: pd.DataFrame, path: str | Path) -> None:
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.suffix.lower() in {".xlsx", ".xls"}:
        df.to_excel(path, index=False)
    else:
        df.to_csv(path, index=False, encoding="utf-8-sig")
    logging.info("Saved table: %s", path)


# -----------------------------------------------------------------------------
# Core calculations
# -----------------------------------------------------------------------------


def relative_change(end_value: pd.Series | np.ndarray, base_value: pd.Series | np.ndarray) -> pd.Series | np.ndarray:
    base = np.asarray(base_value, dtype=float)
    end = np.asarray(end_value, dtype=float)
    with np.errstate(divide="ignore", invalid="ignore"):
        out = 100.0 * (end - base) / base
    return out


def classify_change(value_percent: float, threshold_percent: float) -> str:
    if value_percent > threshold_percent:
        return "increase"
    if value_percent < -threshold_percent:
        return "decrease"
    return "stable"


def direction_symbol(status: str, prefix: str) -> str:
    if status == "increase":
        return f"{prefix}↑"
    if status == "decrease":
        return f"{prefix}↓"
    return f"{prefix}≈"


def coupling_label(g_c: float, g_s: float, threshold_percent: float) -> str:
    c_status = classify_change(g_c, threshold_percent)
    s_status = classify_change(g_s, threshold_percent)
    return f"{direction_symbol(c_status, 'C')}–{direction_symbol(s_status, 'S')}"


def align_tables(cropland: pd.DataFrame, sown: pd.DataFrame) -> tuple[pd.DataFrame, pd.DataFrame]:
    common = sorted(set(cropland["Province"]) & set(sown["Province"]))
    missing_c = sorted(set(sown["Province"]) - set(cropland["Province"]))
    missing_s = sorted(set(cropland["Province"]) - set(sown["Province"]))
    if missing_c:
        logging.warning("Provinces present in sown table but absent in cropland table: %s", missing_c)
    if missing_s:
        logging.warning("Provinces present in cropland table but absent in sown table: %s", missing_s)
    if not common:
        raise ValueError("No overlapping province names between cropland and sown-area tables.")
    c = cropland[cropland["Province"].isin(common)].set_index("Province").loc[common].reset_index()
    s = sown[sown["Province"].isin(common)].set_index("Province").loc[common].reset_index()
    return c, s


def build_province_summary(
    cropland: pd.DataFrame,
    sown: pd.DataFrame,
    start_year: int,
    end_year: int,
    threshold_percent: float,
) -> pd.DataFrame:
    c0 = cropland[str(start_year)].astype(float)
    c1 = cropland[str(end_year)].astype(float)
    s0 = sown[str(start_year)].astype(float)
    s1 = sown[str(end_year)].astype(float)

    r0 = s0 / c0
    r1 = s1 / c1
    delta_c = c1 - c0
    delta_s = s1 - s0
    delta_r = r1 - r0

    g_c = relative_change(c1, c0)
    g_s = relative_change(s1, s0)
    di = g_s - g_c

    extent_effect = r0 * delta_c
    intensity_effect = c0 * delta_r
    interaction_effect = delta_c * delta_r
    reconstructed = extent_effect + intensity_effect + interaction_effect

    rows = []
    for i, province in enumerate(cropland["Province"]):
        label = coupling_label(float(g_c[i]), float(g_s[i]), threshold_percent)
        rows.append(
            {
                "Province": province,
                f"C_{start_year}_kha": c0.iloc[i],
                f"C_{end_year}_kha": c1.iloc[i],
                f"S_{start_year}_kha": s0.iloc[i],
                f"S_{end_year}_kha": s1.iloc[i],
                f"R_{start_year}": r0.iloc[i],
                f"R_{end_year}": r1.iloc[i],
                "delta_C_kha": delta_c.iloc[i],
                "delta_S_kha": delta_s.iloc[i],
                "delta_R": delta_r.iloc[i],
                "gC_percent": g_c[i],
                "gS_percent": g_s[i],
                "decoupling_index_pp": di[i],
                "coupling_type": label,
                "coupling_name": COUPLING_NAMES.get(label, label),
                "cropland_extent_effect_kha": extent_effect.iloc[i],
                "use_intensity_effect_kha": intensity_effect.iloc[i],
                "interaction_effect_kha": interaction_effect.iloc[i],
                "reconstructed_delta_S_kha": reconstructed.iloc[i],
                "decomposition_error_kha": delta_s.iloc[i] - reconstructed.iloc[i],
            }
        )
    return pd.DataFrame(rows)


def build_national_timeseries(
    cropland: pd.DataFrame,
    sown: pd.DataFrame,
    start_year: int,
    end_year: int,
) -> pd.DataFrame:
    rows = []
    base_c = cropland[str(start_year)].sum()
    base_s = sown[str(start_year)].sum()
    for year in range(start_year, end_year + 1):
        c = cropland[str(year)].sum()
        s = sown[str(year)].sum()
        r = s / c
        rows.append(
            {
                "year": year,
                "C_kha": c,
                "S_kha": s,
                "R_S_over_C": r,
                "gC_percent": 100.0 * (c - base_c) / base_c,
                "gS_percent": 100.0 * (s - base_s) / base_s,
                "decoupling_index_pp": 100.0 * (s - base_s) / base_s - 100.0 * (c - base_c) / base_c,
            }
        )
    return pd.DataFrame(rows)


def decompose_between(c0: float, s0: float, c1: float, s1: float) -> dict[str, float]:
    r0 = s0 / c0
    r1 = s1 / c1
    delta_c = c1 - c0
    delta_s = s1 - s0
    delta_r = r1 - r0
    extent = r0 * delta_c
    intensity = c0 * delta_r
    interaction = delta_c * delta_r
    return {
        "delta_C_kha": delta_c,
        "delta_S_kha": delta_s,
        "delta_R": delta_r,
        "cropland_extent_effect_kha": extent,
        "use_intensity_effect_kha": intensity,
        "interaction_effect_kha": interaction,
        "reconstructed_delta_S_kha": extent + intensity + interaction,
        "decomposition_error_kha": delta_s - (extent + intensity + interaction),
    }


def build_national_decompositions(
    national: pd.DataFrame,
    start_year: int,
) -> tuple[pd.DataFrame, pd.DataFrame]:
    annual_rows = []
    cumulative_rows = []
    national = national.sort_values("year").reset_index(drop=True)
    for idx in range(1, len(national)):
        prev = national.iloc[idx - 1]
        cur = national.iloc[idx]
        result = decompose_between(prev.C_kha, prev.S_kha, cur.C_kha, cur.S_kha)
        result["year"] = int(cur.year)
        result["from_year"] = int(prev.year)
        result["to_year"] = int(cur.year)
        annual_rows.append(result)

    base = national[national["year"] == start_year].iloc[0]
    for _, cur in national.iterrows():
        result = decompose_between(base.C_kha, base.S_kha, cur.C_kha, cur.S_kha)
        result["year"] = int(cur.year)
        cumulative_rows.append(result)

    return pd.DataFrame(annual_rows), pd.DataFrame(cumulative_rows)


def build_temporal_diagnostics(
    cropland: pd.DataFrame,
    sown: pd.DataFrame,
    start_year: int,
    end_year: int,
    relative_threshold: float = 300.0,
    ratio_threshold: float = 3.0,
) -> pd.DataFrame:
    """Report extreme relative changes and ratios for transparency."""
    rows = []
    c0 = cropland[str(start_year)].astype(float)
    s0 = sown[str(start_year)].astype(float)
    for year in range(start_year, end_year + 1):
        cy = cropland[str(year)].astype(float)
        sy = sown[str(year)].astype(float)
        gy_c = relative_change(cy, c0)
        gy_s = relative_change(sy, s0)
        ratio = sy / cy
        for i, province in enumerate(cropland["Province"]):
            flag = False
            reasons = []
            if abs(gy_c[i]) > relative_threshold:
                flag = True
                reasons.append("extreme_cropland_relative_change")
            if abs(gy_s[i]) > relative_threshold:
                flag = True
                reasons.append("extreme_sown_relative_change")
            if ratio.iloc[i] > ratio_threshold:
                flag = True
                reasons.append("high_sown_to_cropland_ratio")
            rows.append(
                {
                    "Province": province,
                    "year": year,
                    "C_kha": cy.iloc[i],
                    "S_kha": sy.iloc[i],
                    "R_S_over_C": ratio.iloc[i],
                    "gC_percent_from_base": gy_c[i],
                    "gS_percent_from_base": gy_s[i],
                    "flagged": flag,
                    "flag_reason": ";".join(reasons),
                }
            )
    return pd.DataFrame(rows)


# -----------------------------------------------------------------------------
# Figure functions
# -----------------------------------------------------------------------------


def _axis_limits_with_padding(values: Iterable[float], threshold: float) -> tuple[float, float]:
    finite = np.asarray([v for v in values if np.isfinite(v)], dtype=float)
    if finite.size == 0:
        return -threshold * 1.5, threshold * 1.5
    lo = min(float(np.nanpercentile(finite, 2)), -threshold)
    hi = max(float(np.nanpercentile(finite, 98)), threshold)
    pad = 0.12 * (hi - lo if hi > lo else 1.0)
    return lo - pad, hi + pad


def plot_coupling_scatter(province: pd.DataFrame, output_base: Path, threshold: float, formats: Sequence[str]) -> None:
    fig, ax = plt.subplots(figsize=(7.2, 6.4))
    ax.axhline(0, color=MID_GRAY, lw=0.8, zorder=0)
    ax.axvline(0, color=MID_GRAY, lw=0.8, zorder=0)
    ax.axhspan(-threshold, threshold, color=PALE_GRAY, alpha=0.8, zorder=0)
    ax.axvspan(-threshold, threshold, color=PALE_GRAY, alpha=0.8, zorder=0)
    ax.axhline(threshold, color=MID_GRAY, ls="--", lw=0.8)
    ax.axhline(-threshold, color=MID_GRAY, ls="--", lw=0.8)
    ax.axvline(threshold, color=MID_GRAY, ls="--", lw=0.8)
    ax.axvline(-threshold, color=MID_GRAY, ls="--", lw=0.8)

    for label in COUPLING_ORDER:
        sub = province[province["coupling_type"] == label]
        if sub.empty:
            continue
        ax.scatter(
            sub["gC_percent"],
            sub["gS_percent"],
            s=55,
            color=COUPLING_COLORS[label],
            edgecolor="white",
            linewidth=0.6,
            alpha=0.92,
            label=label,
        )

    ax.set_xlabel("CACD-derived cropland extent change relative to base year (%)")
    ax.set_ylabel("Statistical crop sown-area change relative to base year (%)")
    ax.set_title("Coupling between physical cropland extent and annual planting activity")
    ax.set_xlim(_axis_limits_with_padding(province["gC_percent"], threshold))
    ax.set_ylim(_axis_limits_with_padding(province["gS_percent"], threshold))
    legend_handles = [
        Line2D([0], [0], marker="o", color="none", markerfacecolor=COUPLING_COLORS[k], markeredgecolor="white", label=k)
        for k in COUPLING_ORDER
        if k in set(province["coupling_type"])
    ]
    ax.legend(handles=legend_handles, title="Coupling type", loc="best", frameon=True, ncol=1)
    despine(ax)
    save_figure(fig, output_base, formats)


def plot_phase_space(national: pd.DataFrame, output_base: Path, threshold: float, formats: Sequence[str]) -> None:
    fig, ax = plt.subplots(figsize=(7.2, 6.2))
    ax.axhline(0, color=MID_GRAY, lw=0.8, zorder=0)
    ax.axvline(0, color=MID_GRAY, lw=0.8, zorder=0)
    ax.axhline(threshold, color=MID_GRAY, lw=0.8, ls="--")
    ax.axhline(-threshold, color=MID_GRAY, lw=0.8, ls="--")
    ax.axvline(threshold, color=MID_GRAY, lw=0.8, ls="--")
    ax.axvline(-threshold, color=MID_GRAY, lw=0.8, ls="--")
    ax.axhspan(-threshold, threshold, color=PALE_GRAY, alpha=0.55, zorder=0)
    ax.axvspan(-threshold, threshold, color=PALE_GRAY, alpha=0.35, zorder=0)

    sc = ax.scatter(
        national["gC_percent"],
        national["gS_percent"],
        c=national["year"],
        cmap="viridis",
        s=58,
        edgecolor="white",
        linewidth=0.6,
        zorder=3,
    )
    ax.plot(national["gC_percent"], national["gS_percent"], color=CHARCOAL, lw=1.2, alpha=0.55, zorder=2)

    first = national.iloc[0]
    last = national.iloc[-1]
    ax.text(first.gC_percent, first.gS_percent, str(int(first.year)), fontsize=9, ha="right", va="bottom")
    ax.text(last.gC_percent, last.gS_percent, str(int(last.year)), fontsize=9, ha="left", va="top")

    # Add a small arrow to clarify temporal direction.
    if len(national) > 2:
        p1 = national.iloc[-3]
        p2 = national.iloc[-1]
        ax.annotate(
            "",
            xy=(p2.gC_percent, p2.gS_percent),
            xytext=(p1.gC_percent, p1.gS_percent),
            arrowprops=dict(arrowstyle="->", lw=1.1, color=CHARCOAL),
        )

    cbar = fig.colorbar(sc, ax=ax, pad=0.02)
    cbar.set_label("Year")
    ax.set_xlabel("CACD-derived cropland extent change relative to 2000 (%)")
    ax.set_ylabel("Statistical crop sown-area change relative to 2000 (%)")
    ax.set_title("National phase-space trajectory")
    ax.set_xlim(_axis_limits_with_padding(national["gC_percent"], threshold))
    ax.set_ylim(_axis_limits_with_padding(national["gS_percent"], threshold))
    despine(ax)
    save_figure(fig, output_base, formats)


def plot_cumulative_decomposition(cumulative: pd.DataFrame, output_base: Path, formats: Sequence[str]) -> None:
    fig, ax = plt.subplots(figsize=(8.2, 5.6))
    x = cumulative["year"].values
    bottom_pos = np.zeros_like(x, dtype=float)
    bottom_neg = np.zeros_like(x, dtype=float)
    terms = [
        ("Cropland-extent effect", "cropland_extent_effect_kha"),
        ("Use-intensity effect", "use_intensity_effect_kha"),
        ("Interaction effect", "interaction_effect_kha"),
    ]
    for label, col in terms:
        values = cumulative[col].values.astype(float)
        pos = np.where(values >= 0, values, 0.0)
        neg = np.where(values < 0, values, 0.0)
        ax.bar(x, pos, bottom=bottom_pos, width=0.72, color=EFFECT_COLORS[label], label=label)
        ax.bar(x, neg, bottom=bottom_neg, width=0.72, color=EFFECT_COLORS[label])
        bottom_pos += pos
        bottom_neg += neg
    ax.plot(x, cumulative["delta_S_kha"], color=CHARCOAL, lw=2.4, marker="o", ms=4, label="Observed ΔS")
    ax.axhline(0, color=CHARCOAL, lw=0.8)
    ax.set_xlabel("Year")
    ax.set_ylabel("Cumulative change in crop sown area (kha)")
    ax.set_title("Exact decomposition of national crop sown-area change")
    ax.legend(frameon=True, loc="best")
    despine(ax)
    save_figure(fig, output_base, formats)


def plot_temporal_envelope(temporal: pd.DataFrame, output_base: Path, formats: Sequence[str]) -> None:
    metrics = [
        ("gC_percent_from_base", "Cropland extent change from 2000 (%)", NAVY),
        ("gS_percent_from_base", "Crop sown-area change from 2000 (%)", TEAL),
        ("R_S_over_C", "Agricultural-use intensity proxy (S/C)", PLUM),
    ]
    fig, axes = plt.subplots(1, 3, figsize=(15.5, 4.8), sharex=True)
    for ax, (col, ylabel, color) in zip(axes, metrics):
        stat = (
            temporal.groupby("year")[col]
            .quantile([0.10, 0.25, 0.50, 0.75, 0.90])
            .unstack()
            .reset_index()
        )
        years = stat["year"].values
        ax.fill_between(years, stat[0.10], stat[0.90], color=color, alpha=0.12, label="10–90%")
        ax.fill_between(years, stat[0.25], stat[0.75], color=color, alpha=0.24, label="IQR")
        ax.plot(years, stat[0.50], color=color, lw=2.5, label="Median")
        ax.set_ylabel(ylabel)
        ax.set_xlabel("Year")
        ax.grid(axis="y", color=LIGHT_GRAY, lw=0.6)
        despine(ax)
    axes[0].legend(frameon=True, loc="best")
    fig.suptitle("Robust temporal envelopes across provinces", y=1.02, fontweight="bold")
    save_figure(fig, output_base, formats)


# -----------------------------------------------------------------------------
# Workflow
# -----------------------------------------------------------------------------


def run_diagnostics(
    cropland_file: str | Path,
    sown_file: str | Path,
    output_dir: str | Path,
    start_year: int = 2000,
    end_year: int = 2023,
    stable_threshold_percent: float = 5.0,
    sheet_name: str | int | None = 0,
    input_scale_to_kha: float = 1.0,
    figure_dpi: int = 300,
    save_formats: Sequence[str] = ("png", "pdf"),
) -> DiagnosticOutputs:
    set_publication_style(figure_dpi)
    output_dir = Path(output_dir)
    tables_dir = output_dir / "tables"
    figures_dir = output_dir / "figures"
    tables_dir.mkdir(parents=True, exist_ok=True)
    figures_dir.mkdir(parents=True, exist_ok=True)

    cropland = read_year_table(cropland_file, sheet_name, start_year, end_year, input_scale_to_kha)
    sown = read_year_table(sown_file, sheet_name, start_year, end_year, input_scale_to_kha)
    cropland, sown = align_tables(cropland, sown)

    province = build_province_summary(cropland, sown, start_year, end_year, stable_threshold_percent)
    national = build_national_timeseries(cropland, sown, start_year, end_year)
    annual, cumulative = build_national_decompositions(national, start_year)
    coupling_counts = (
        province.groupby(["coupling_type", "coupling_name"], dropna=False)
        .size()
        .reset_index(name="n_provinces")
        .sort_values("coupling_type")
    )
    temporal = build_temporal_diagnostics(cropland, sown, start_year, end_year)

    write_table(province, tables_dir / "province_summary_coupling_decomposition.csv")
    write_table(national, tables_dir / "national_timeseries_coupling.csv")
    write_table(annual, tables_dir / "national_annual_sown_area_decomposition.csv")
    write_table(cumulative, tables_dir / "national_cumulative_sown_area_decomposition.csv")
    write_table(coupling_counts, tables_dir / "coupling_type_counts.csv")
    write_table(temporal, tables_dir / "temporal_value_diagnostics_all.csv")
    write_table(temporal[temporal["flagged"]], tables_dir / "temporal_value_diagnostics_flagged.csv")

    with pd.ExcelWriter(tables_dir / "integrated_cacd_sown_experiment_results.xlsx") as writer:
        province.to_excel(writer, sheet_name="province_summary", index=False)
        national.to_excel(writer, sheet_name="national_timeseries", index=False)
        annual.to_excel(writer, sheet_name="annual_decomposition", index=False)
        cumulative.to_excel(writer, sheet_name="cumulative_decomposition", index=False)
        coupling_counts.to_excel(writer, sheet_name="coupling_counts", index=False)
        temporal.to_excel(writer, sheet_name="temporal_diagnostics", index=False)

    plot_coupling_scatter(province, figures_dir / "fig2_coupling_typology", stable_threshold_percent, save_formats)
    plot_phase_space(national, figures_dir / "fig3_phase_space", stable_threshold_percent, save_formats)
    plot_cumulative_decomposition(cumulative, figures_dir / "fig3_cumulative_decomposition", save_formats)
    plot_temporal_envelope(temporal, figures_dir / "fig4_temporal_envelope", save_formats)

    note = (
        "Interpretation note:\n"
        "C denotes physical cropland extent derived from CACD. S denotes official statistical crop sown area.\n"
        "R = S/C is used only as an agricultural-use intensity proxy, not as a strict multiple-cropping index.\n"
        "The decomposition Delta S = R0*Delta C + C0*Delta R + Delta C*Delta R is exact.\n"
        "Stable status is defined by the user-specified threshold and is not equivalent to zero change.\n"
    )
    (output_dir / "interpretation_note.txt").write_text(note, encoding="utf-8")

    return DiagnosticOutputs(province, national, annual, cumulative, coupling_counts, temporal)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Detailed cropland extent--crop sown area diagnostic workflow.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    parser.add_argument("--cropland", required=True, help="Province-by-year CACD-derived cropland extent table.")
    parser.add_argument("--sown", required=True, help="Province-by-year official crop sown-area table.")
    parser.add_argument("--output-dir", required=True, help="Directory for all output tables and figures.")
    parser.add_argument("--start-year", type=int, default=2000)
    parser.add_argument("--end-year", type=int, default=2023)
    parser.add_argument("--stable-threshold", type=float, default=5.0, help="Stable threshold in percent.")
    parser.add_argument("--sheet-name", default=0, help="Excel sheet name or index. Ignored for CSV files.")
    parser.add_argument("--input-scale-to-kha", type=float, default=1.0, help="Multiplier used to convert input area values to kha.")
    parser.add_argument("--dpi", type=int, default=300)
    parser.add_argument("--formats", nargs="+", default=["png", "pdf"], help="Figure formats to save.")
    parser.add_argument("--quiet", action="store_true", help="Reduce logging output.")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    configure_logging(not args.quiet)
    run_diagnostics(
        cropland_file=args.cropland,
        sown_file=args.sown,
        output_dir=args.output_dir,
        start_year=args.start_year,
        end_year=args.end_year,
        stable_threshold_percent=args.stable_threshold,
        sheet_name=args.sheet_name,
        input_scale_to_kha=args.input_scale_to_kha,
        figure_dpi=args.dpi,
        save_formats=tuple(args.formats),
    )


if __name__ == "__main__":
    main()
