#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Publication-figure helper script for the cropland transformation workflow.

This script does not recalculate the scientific indicators. It reads output
CSV/XLSX files generated by earlier steps and creates integrated figures that are
useful for manuscript checking, supplementary materials and reviewer responses.

Subcommands
-----------
phase-space      Plot national cropland extent--sown area phase-space trajectory.
decomposition    Plot cumulative crop sown-area decomposition.
heatmap          Plot GTWR/GWR/TWR local coefficient heatmap.
summary-radar    Plot normalized socio-environmental trajectories for Fig. 5-like panels.
"""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Sequence

import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt


def set_style(dpi: int = 300) -> None:
    mpl.rcParams.update({"font.family": "serif", "font.serif": ["Times New Roman", "DejaVu Serif"], "figure.dpi": dpi, "savefig.dpi": dpi, "pdf.fonttype": 42, "ps.fonttype": 42, "axes.unicode_minus": False})


def read_table(path: str | Path) -> pd.DataFrame:
    path = Path(path)
    if path.suffix.lower() in {".xlsx", ".xls"}:
        return pd.read_excel(path)
    return pd.read_csv(path)


def save(fig, output_base: str | Path) -> None:
    output_base = Path(output_base)
    output_base.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(output_base.with_suffix(".png"), bbox_inches="tight", facecolor="white")
    fig.savefig(output_base.with_suffix(".pdf"), bbox_inches="tight", facecolor="white")
    plt.close(fig)


def plot_phase_space(national: pd.DataFrame, output_base: str | Path, threshold: float = 5.0) -> None:
    fig, ax = plt.subplots(figsize=(7.2, 6.0))
    ax.axhspan(-threshold, threshold, color="#F2F2F2", alpha=0.8, zorder=0)
    ax.axvspan(-threshold, threshold, color="#F2F2F2", alpha=0.45, zorder=0)
    for v in [-threshold, 0, threshold]:
        ax.axhline(v, color="#B8B8B8", lw=0.8, ls="--" if v else "-")
        ax.axvline(v, color="#B8B8B8", lw=0.8, ls="--" if v else "-")
    sc = ax.scatter(national["gC_percent"], national["gS_percent"], c=national["year"], cmap="viridis", s=60, edgecolor="white", linewidth=0.6)
    ax.plot(national["gC_percent"], national["gS_percent"], color="#222222", alpha=0.55, lw=1.4)
    ax.text(national.iloc[0]["gC_percent"], national.iloc[0]["gS_percent"], str(int(national.iloc[0]["year"])), ha="right", va="bottom")
    ax.text(national.iloc[-1]["gC_percent"], national.iloc[-1]["gS_percent"], str(int(national.iloc[-1]["year"])), ha="left", va="top")
    ax.set_xlabel("CACD-derived cropland extent change relative to 2000 (%)")
    ax.set_ylabel("Statistical crop sown-area change relative to 2000 (%)")
    ax.set_title("National phase-space trajectory")
    fig.colorbar(sc, ax=ax, pad=0.02, label="Year")
    save(fig, output_base)


def plot_decomposition(cumulative: pd.DataFrame, output_base: str | Path) -> None:
    fig, ax = plt.subplots(figsize=(8.2, 5.2))
    x = cumulative["year"].values
    terms = [
        ("cropland_extent_effect_kha", "Cropland-extent effect", "#173A5E"),
        ("use_intensity_effect_kha", "Use-intensity effect", "#2A9D8F"),
        ("interaction_effect_kha", "Interaction effect", "#D9A441"),
    ]
    pos_base = np.zeros(len(cumulative))
    neg_base = np.zeros(len(cumulative))
    for col, label, color in terms:
        vals = cumulative[col].values.astype(float)
        pos = np.where(vals >= 0, vals, 0)
        neg = np.where(vals < 0, vals, 0)
        ax.bar(x, pos, bottom=pos_base, width=0.75, color=color, label=label)
        ax.bar(x, neg, bottom=neg_base, width=0.75, color=color)
        pos_base += pos
        neg_base += neg
    if "delta_S_kha" in cumulative.columns:
        ax.plot(x, cumulative["delta_S_kha"], color="#222222", marker="o", lw=2.2, label="Observed ΔS")
    ax.axhline(0, color="#222222", lw=0.8)
    ax.set_xlabel("Year")
    ax.set_ylabel("Cumulative change in crop sown area (kha)")
    ax.legend(frameon=True)
    save(fig, output_base)


def plot_heatmap(coefficients: pd.DataFrame, output_base: str | Path, coefficient_columns: Sequence[str]) -> None:
    cols = [c for c in coefficient_columns if c in coefficients.columns]
    if not cols:
        raise ValueError(f"None of the coefficient columns were found: {coefficient_columns}")
    if "Province" in coefficients.columns and "year" in coefficients.columns:
        labels = coefficients["Province"].astype(str) + "_" + coefficients["year"].astype(str)
    else:
        labels = np.arange(len(coefficients)).astype(str)
    mat = coefficients[cols].apply(pd.to_numeric, errors="coerce")
    vmax = max(0.1, np.nanpercentile(np.abs(mat.values), 98))
    fig, ax = plt.subplots(figsize=(7.0, max(5.0, 0.12 * len(mat))))
    im = ax.imshow(mat.values, cmap="RdBu_r", vmin=-vmax, vmax=vmax, aspect="auto")
    ax.set_xticks(np.arange(len(cols)))
    ax.set_xticklabels([c.replace("coef_", "") for c in cols], rotation=45, ha="right")
    step = max(1, len(labels) // 30)
    ax.set_yticks(np.arange(0, len(labels), step))
    ax.set_yticklabels(labels[::step])
    fig.colorbar(im, ax=ax, pad=0.02, label="Normalized/local coefficient")
    save(fig, output_base)


def plot_summary_radar(table: pd.DataFrame, output_base: str | Path, year_col: str, value_columns: Sequence[str]) -> None:
    # Normalize each variable to [0,1] only for visualization; raw values are not altered.
    df = table.sort_values(year_col).copy()
    angles = np.linspace(0, 2 * np.pi, len(value_columns), endpoint=False).tolist()
    angles += angles[:1]
    fig = plt.figure(figsize=(7.2, 7.2))
    ax = fig.add_subplot(111, polar=True)
    years = df[year_col].tolist()
    selected_years = years[:: max(1, len(years) // 6)]
    if years[-1] not in selected_years:
        selected_years.append(years[-1])
    for year in selected_years:
        row = df[df[year_col] == year].iloc[0]
        vals = []
        for col in value_columns:
            series = pd.to_numeric(df[col], errors="coerce")
            denom = series.max() - series.min()
            vals.append(0.5 if denom == 0 else (row[col] - series.min()) / denom)
        vals += vals[:1]
        ax.plot(angles, vals, lw=1.6, label=str(year))
    ax.set_xticks(angles[:-1])
    ax.set_xticklabels(value_columns)
    ax.set_title("Normalized socio-environmental trajectories")
    ax.legend(loc="upper right", bbox_to_anchor=(1.25, 1.10), frameon=True)
    save(fig, output_base)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Plot publication and diagnostic figures from workflow outputs.")
    sub = parser.add_subparsers(dest="command", required=True)
    p = sub.add_parser("phase-space")
    p.add_argument("--national-timeseries", required=True)
    p.add_argument("--output-base", required=True)
    p.add_argument("--threshold", type=float, default=5.0)
    p = sub.add_parser("decomposition")
    p.add_argument("--cumulative-decomposition", required=True)
    p.add_argument("--output-base", required=True)
    p = sub.add_parser("heatmap")
    p.add_argument("--coefficients", required=True)
    p.add_argument("--output-base", required=True)
    p.add_argument("--coefficient-columns", nargs="+", default=["coef_SSN", "coef_GM", "coef_IPLG", "coef_RW"])
    p = sub.add_parser("summary-radar")
    p.add_argument("--table", required=True)
    p.add_argument("--output-base", required=True)
    p.add_argument("--year-col", default="year")
    p.add_argument("--value-columns", nargs="+", required=True)
    parser.add_argument("--dpi", type=int, default=300)
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    set_style(args.dpi)
    if args.command == "phase-space":
        plot_phase_space(read_table(args.national_timeseries), args.output_base, args.threshold)
    elif args.command == "decomposition":
        plot_decomposition(read_table(args.cumulative_decomposition), args.output_base)
    elif args.command == "heatmap":
        plot_heatmap(read_table(args.coefficients), args.output_base, args.coefficient_columns)
    elif args.command == "summary-radar":
        plot_summary_radar(read_table(args.table), args.output_base, args.year_col, args.value_columns)


if __name__ == "__main__":
    main()
